# Set base image for Nginx
FROM nginx:latest

# Copy Nginx '.conf' file
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# Set working directory
WORKDIR /var/www/html

# Expose ports
EXPOSE 80

# Start Nginx
CMD nginx -g "daemon off;"
